class CitizenStrings {
  static const Map<String, Map<String, String>>
  _values = <String, Map<String, String>>{
    'en': <String, String>{
      'title_dashboard': 'Citizen Dashboard',
      'title_alerts': 'Alerts',
      'title_report': 'Report Flooding',
      'title_safe_zones': 'Safe Zones',
      'title_request_help': 'Request Help',
      'title_my_reports': 'My Reports',
      'title_trust': 'App Language',
      'menu': 'Citizen Menu',
      'navigation': 'Navigation',
      'dashboard': 'Dashboard',
      'alerts': 'Alerts',
      'report': 'Report Flooding',
      'safe_zones': 'Safe Zones',
      'request_help': 'Request Help',
      'my_reports': 'My Reports',
      'trust': 'App Language',
      'language_tooltip': 'Language',
      'retry': 'Retry',
      'call': 'Call',
      'time_unknown': 'unknown',
      'time_just_now': 'just now',
      'time_min_ago': '{value} min ago',
      'time_hr_ago': '{value} hr ago',
      'time_day_ago': '{value} day(s) ago',
      'dash_call_failed': 'Could not place call to {number}',
      'dash_location_copied': 'Location copied for sharing.',
      'dash_summary_fetch_failed': 'Could not fetch live summary.',
      'dash_stay_alert_title': 'Stay Alert. Report Flooding Fast.',
      'dash_stay_alert_subtitle':
          'Use this app to submit flood photos, share water level, and find safe zones nearby.',
      'dash_btn_report': 'Report Flooding Now',
      'dash_btn_alerts': 'View Alerts',
      'dash_btn_safe_zones': 'Open Safe Zones Map',
      'dash_btn_request_help': 'Request Help',
      'dash_btn_my_reports': 'My Report History',
      'dash_live_snapshot': 'Live Snapshot',
      'dash_loading_live': 'Loading live information...',
      'dash_active_safe_zones': 'Active safe zones available now: {count}',
      'dash_active_alerts': 'Live alerts now: {count}',
      'dash_safe_zones_updated': 'Safe zones data last updated: {ago}',
      'dash_alerts_fetch_failed': 'Could not fetch live alerts.',
      'dash_no_live_alerts': 'No live alerts right now.',
      'dash_view_alerts_feed': 'View Alerts Feed',
      'dash_what_to_report': 'What To Report',
      'dash_report_point_1':
          '1. Capture clear photos of roads and water movement.',
      'dash_report_point_2':
          '2. Select the closest zone ID and send current water level.',
      'dash_report_point_3': '3. Submit updates again if flooding worsens.',
      'dash_immediate_safety': 'Immediate Safety',
      'dash_safety_point_1': 'Avoid low-lying roads and underpasses.',
      'dash_safety_point_2': 'Move to marked safe zones and stay updated.',
      'dash_safety_point_3': 'Call local emergency services for urgent danger.',
      'dash_safety_point_4':
          'Keep phone battery above 50% when heavy rain starts.',
      'dash_safety_point_5':
          'Share verified location with family before moving.',
      'dash_safety_freshness': 'Safe zone data freshness: updated {ago}.',
      'dash_helplines': 'Emergency Helplines',
      'dash_select_area': 'Select your area for district-wise guidance:',
      'dash_area_label': 'Area',
      'dash_helpline_national': 'National Emergency Response',
      'dash_helpline_fire': 'Fire Brigade',
      'dash_helpline_ambulance': 'Ambulance / Medical Emergency',
      'dash_helpline_area_support': '{area} Emergency Support',
      'dash_helpline_tip':
          'Tip: Share your exact area while calling for faster response.',
      'dash_live_location_title': 'Live Location for Help',
      'dash_live_location_desc':
          'Use this only when needed to quickly share your exact location with responders or family.',
      'dash_fetching_location': 'Fetching location...',
      'dash_get_live_location': 'Get Live Location',
      'dash_location_service_disabled': 'Location service is disabled.',
      'dash_location_permission_denied': 'Location permission denied.',
      'dash_location_fetch_failed': 'Unable to fetch live location.',
      'dash_lat_lng': 'Lat {lat}, Lng {lng}',
      'dash_copy_help': 'Copy Help Message',
      'dash_open_maps': 'Open in Maps',
      'dash_help_message_template':
          'Emergency help needed. Current location: {url}',
      'dash_emergency_actions': 'Emergency Actions',
      'dash_quick_guide_title': 'Quick Guide',
      'dash_quick_step_1_title': '1. Check Alerts',
      'dash_quick_step_1_subtitle':
          'Open Alerts to confirm current risk in your area.',
      'dash_quick_step_2_title': '2. Report Flooding',
      'dash_quick_step_2_subtitle':
          'Submit water level and flood photo from your location.',
      'dash_quick_step_3_title': '3. Request Help / Safe Zones',
      'dash_quick_step_3_subtitle':
          'Use Help for urgent aid, Safe Zones for evacuation.',
      'help_title': 'Request Help',
      'help_desc':
          'One-tap flow for urgent support. Select category, add contact number, and optional location.',
      'help_category_medical': 'Medical',
      'help_category_evacuation': 'Evacuation',
      'help_category_food_water': 'Food/Water',
      'help_contact_label': 'Contact Number',
      'help_contact_hint': 'Example: 9876543210',
      'help_attach_location_optional': 'Attach Live Location (optional)',
      'help_detecting': 'Detecting...',
      'help_live_location_attached': 'Live location attached.',
      'help_live_location_fetch_failed': 'Could not fetch live location.',
      'help_send': 'Send Help Request',
      'help_sending': 'Sending...',
      'help_invalid_contact': 'Enter a valid contact number.',
      'help_sent_success': 'Help request sent successfully.',
      'help_rejected': 'Help request was rejected by server.',
      'help_saved_offline': 'No network. Help request saved offline.',
      'help_location_service_disabled': 'Location service disabled',
      'help_location_permission_denied': 'Location permission denied',
      'help_tracking_title': 'Help Request Tracking',
      'help_tracking_empty': 'No help requests tracked yet.',
      'help_tracking_updated': 'Help request status refreshed.',
      'help_status_sent': 'SENT',
      'help_status_received': 'RECEIVED',
      'help_status_assigned': 'ASSIGNED',
      'help_status_closed': 'CLOSED',
      'help_status_pending': 'PENDING OFFLINE',
      'help_status_failed': 'FAILED',
      'help_track_created': 'Created {ago}',
      'help_pending_title': 'Pending Offline Help Requests',
      'help_pending_count': 'Pending requests: {count}',
      'help_sync_pending_button': 'Sync Pending Requests ({count})',
      'help_syncing': 'Syncing...',
      'help_sync_none': 'No pending help requests to sync.',
      'help_sync_summary':
          'Synced {synced} request(s), failed {failed}, pending {pending}.',
      'report_loc_service_disabled': 'Location service disabled',
      'report_loc_permission_denied': 'Location permission denied',
      'report_sync_none': 'No pending offline reports to sync.',
      'report_sync_summary':
          'Synced {synced} report(s), failed {failed}, pending {pending}.',
      'report_invalid_pincode': 'Please enter a valid 6-digit pincode.',
      'report_enter_custom_zone': 'Please enter a custom zone ID.',
      'report_detected_area': 'Detected area: {city}, {area} ({pincode})',
      'report_gps_custom_created':
          'Could not map to known region. Custom GPS zone ID created.',
      'report_unable_detect_location': 'Unable to detect current location.',
      'report_unable_access_camera_gallery': 'Unable to access camera/gallery.',
      'report_submission_failed_water': 'Failed to submit water level.',
      'report_saved_offline_pending':
          'No network. Water level saved offline. Pending: {count}.',
      'report_photo_required': 'Please capture or choose a flood photo.',
      'report_submission_failed_photo': 'Failed to submit flood photo.',
      'report_section_location_zone': 'Location Zone',
      'report_mode_area_pincode': 'Area + Pincode',
      'report_mode_custom': 'Custom ID',
      'report_detecting_location': 'Detecting location...',
      'report_use_gps_autodetect': 'Use GPS to Auto Detect Area',
      'report_city_district': 'City / District',
      'report_area_suggestions': 'Area Suggestions',
      'report_clear_selected_area': 'Clear selected area',
      'report_suggested_areas': 'Suggested Areas',
      'report_suggested_helper':
          'Pick from list, or type your own region below.',
      'report_select_area_optional': 'Select area (optional)',
      'report_locality_label': 'Region / Locality (manual optional)',
      'report_locality_hint': 'Enter your region, area, or neighborhood',
      'report_locality_helper':
          'Use this if your region is not in the dropdown.',
      'report_pincode_label': 'Pincode',
      'report_pincode_hint': '6-digit pincode',
      'report_my_area_use': 'Use My Area',
      'report_my_area_save': 'Save My Area',
      'report_my_area_clear_saved': 'Clear Saved Area',
      'report_my_area_saved': 'Saved as your default area.',
      'report_my_area_applied': 'Applied your saved area.',
      'report_my_area_cleared': 'Saved default area cleared.',
      'report_my_area_missing': 'No saved area found yet.',
      'report_generated_zone_id': 'Generated zone ID: {zone}',
      'report_custom_zone_id_label': 'Custom Zone ID',
      'report_custom_zone_id_hint': 'Example: WARD-12 or GPS-19.0178-72.8478',
      'report_section_flood_photo': 'Flood Photo',
      'report_camera': 'Camera',
      'report_gallery': 'Gallery',
      'report_selected_file': 'Selected: {name}',
      'report_submitting': 'Submitting...',
      'report_submit_flood_photo': 'Submit Flood Photo',
      'report_section_flooding_level': 'Flooding Level',
      'report_submit_water_level': 'Submit Water Level',
      'report_syncing_pending': 'Syncing pending...',
      'report_sync_pending_button': 'Sync Pending Water Reports ({count})',
      'alerts_load_failed': 'Failed to load alerts.',
      'alerts_empty': 'No alerts available right now.',
      'alerts_offline_banner': 'Offline mode: showing last saved alerts.',
      'alerts_feed_title': 'Alerts Feed',
      'alerts_count': '{count} alert(s)',
      'alerts_updated': 'Updated: {ago}',
      'alerts_channel': 'Channel: {channel}',
      'safezones_load_failed': 'Failed to load safe zones.',
      'safezones_unavailable_title': 'Safe zones are temporarily unavailable.',
      'safezones_unavailable_help':
          'Check network and retry. You can also pull down to refresh this page.',
      'safezones_retry_hint':
          'If saved safe zones are available, they will show automatically.',
      'safezones_empty': 'No active safe zones available right now.',
      'safezones_offline_banner':
          'Offline mode: showing last saved safe zones.',
      'safezones_locating': 'Locating...',
      'safezones_use_location': 'Use My Location',
      'safezones_distance_hidden': 'Distance hidden until location is enabled.',
      'safezones_distance_shown': 'Distance now shown from your location.',
      'safezones_last_updated': 'Safe zones last updated: {ago}',
      'safezones_nearest': 'Nearest safe zone: {zoneId}',
      'safezones_distance_eta': 'Distance: {km} km | ETA: ~{eta} min',
      'safezones_active_count': 'Active safe zones: {count}',
      'safezones_unnamed_zone': 'Unnamed Zone',
      'safezones_coords': 'Lat {lat}, Lng {lng}',
      'safezones_area_pincode': 'Area: {area} | Pincode: {pincode}',
      'safezones_source_confidence':
          'Source: {source} | Confidence: {confidence}',
      'safezones_area_unavailable': 'Area unavailable',
      'safezones_location_fetch_failed': 'Unable to fetch current location.',
      'safezones_open_route': 'Open Safe Route',
      'safezones_route_tip':
          'Use main roads and avoid visibly flooded lanes while moving.',
      'safezones_route_open_failed': 'Could not open route in maps.',
      'myreports_load_failed': 'Unable to load report history.',
      'myreports_title': 'My Reports',
      'myreports_count': '{count} report(s)',
      'myreports_synced': 'Synced: {count}',
      'myreports_pending': 'Pending: {count}',
      'myreports_failed': 'Failed: {count}',
      'myreports_empty': 'No report history yet.',
      'myreports_type_water_level': 'Water Level',
      'myreports_type_flood_photo': 'Flood Photo',
      'myreports_status_synced': 'SYNCED',
      'myreports_status_pending': 'PENDING',
      'myreports_status_failed': 'FAILED',
      'myreports_zone': 'Zone: {zone}',
      'myreports_level': 'Level: {level}',
      'myreports_created': 'Created {ago}',
      'myreports_updated': 'Updated {ago}',
      'trust_title': 'App Language',
      'trust_desc':
          'Choose your preferred language for clearer instructions during emergencies.',
      'trust_language_label': 'Language',
      'trust_data_saver_title': 'Data Saver Mode',
      'trust_data_saver_desc':
          'Reduces background refresh of Alerts and Safe Zones to save data.',
      'lang_english': 'English',
      'lang_hindi': 'Hindi',
      'lang_marathi': 'Marathi',
    },
    'hi': <String, String>{
      'title_dashboard': 'नागरिक डैशबोर्ड',
      'title_alerts': 'अलर्ट',
      'title_report': 'बाढ़ रिपोर्ट',
      'title_safe_zones': 'सुरक्षित क्षेत्र',
      'title_request_help': 'मदद अनुरोध',
      'title_my_reports': 'मेरी रिपोर्ट',
      'title_trust': 'ऐप भाषा',
      'menu': 'नागरिक मेनू',
      'navigation': 'नेविगेशन',
      'dashboard': 'डैशबोर्ड',
      'alerts': 'अलर्ट',
      'report': 'बाढ़ रिपोर्ट',
      'safe_zones': 'सुरक्षित क्षेत्र',
      'request_help': 'मदद अनुरोध',
      'my_reports': 'मेरी रिपोर्ट',
      'trust': 'ऐप भाषा',
      'language_tooltip': 'भाषा',
      'retry': 'फिर से प्रयास करें',
      'call': 'कॉल',
      'time_unknown': 'अज्ञात',
      'time_just_now': 'अभी',
      'time_min_ago': '{value} मिनट पहले',
      'time_hr_ago': '{value} घंटे पहले',
      'time_day_ago': '{value} दिन पहले',
      'dash_call_failed': '{number} पर कॉल नहीं हो सकी',
      'dash_location_copied': 'लोकेशन शेयर करने के लिए कॉपी कर दी गई है।',
      'dash_summary_fetch_failed': 'लाइव सारांश नहीं मिल सका।',
      'dash_stay_alert_title': 'सतर्क रहें। बाढ़ की रिपोर्ट तुरंत करें।',
      'dash_stay_alert_subtitle':
          'इस ऐप से बाढ़ की फोटो भेजें, पानी का स्तर साझा करें और पास के सुरक्षित क्षेत्र देखें।',
      'dash_btn_report': 'अभी बाढ़ रिपोर्ट करें',
      'dash_btn_alerts': 'अलर्ट देखें',
      'dash_btn_safe_zones': 'सुरक्षित क्षेत्र मानचित्र खोलें',
      'dash_btn_request_help': 'मदद मांगें',
      'dash_btn_my_reports': 'मेरी रिपोर्ट हिस्ट्री',
      'dash_live_snapshot': 'लाइव स्नैपशॉट',
      'dash_loading_live': 'लाइव जानकारी लोड हो रही है...',
      'dash_active_safe_zones': 'अभी उपलब्ध सुरक्षित क्षेत्र: {count}',
      'dash_active_alerts': 'अभी लाइव अलर्ट: {count}',
      'dash_safe_zones_updated': 'सुरक्षित क्षेत्र डेटा अंतिम अपडेट: {ago}',
      'dash_alerts_fetch_failed': 'लाइव अलर्ट नहीं मिल सके।',
      'dash_no_live_alerts': 'अभी कोई लाइव अलर्ट नहीं है।',
      'dash_view_alerts_feed': 'अलर्ट फीड देखें',
      'dash_what_to_report': 'क्या रिपोर्ट करें',
      'dash_report_point_1': '1. सड़कों और पानी की गति की स्पष्ट फोटो लें।',
      'dash_report_point_2':
          '2. सबसे नज़दीकी ज़ोन आईडी चुनें और पानी का वर्तमान स्तर भेजें।',
      'dash_report_point_3': '3. बाढ़ बढ़े तो दोबारा अपडेट भेजें।',
      'dash_immediate_safety': 'तुरंत सुरक्षा',
      'dash_safety_point_1': 'नीचे वाली सड़कों और अंडरपास से बचें।',
      'dash_safety_point_2':
          'चिन्हित सुरक्षित क्षेत्रों में जाएं और अपडेट देखें।',
      'dash_safety_point_3': 'तत्काल खतरे में स्थानीय आपात सेवाओं को कॉल करें।',
      'dash_safety_point_4':
          'भारी बारिश शुरू होते ही फोन बैटरी 50% से ऊपर रखें।',
      'dash_safety_point_5':
          'चलने से पहले परिवार के साथ सत्यापित लोकेशन साझा करें।',
      'dash_safety_freshness':
          'सुरक्षित क्षेत्र डेटा ताज़गी: {ago} पहले अपडेट।',
      'dash_helplines': 'आपातकालीन हेल्पलाइन',
      'dash_select_area': 'जिला-वार मार्गदर्शन के लिए अपना क्षेत्र चुनें:',
      'dash_area_label': 'क्षेत्र',
      'dash_helpline_national': 'राष्ट्रीय आपातकालीन सेवा',
      'dash_helpline_fire': 'फायर ब्रिगेड',
      'dash_helpline_ambulance': 'एंबुलेंस / मेडिकल इमरजेंसी',
      'dash_helpline_area_support': '{area} आपातकालीन सहायता',
      'dash_helpline_tip':
          'टिप: तेज प्रतिक्रिया के लिए कॉल करते समय अपना सटीक क्षेत्र बताएं।',
      'dash_live_location_title': 'मदद के लिए लाइव लोकेशन',
      'dash_live_location_desc':
          'इसे केवल जरूरत पर उपयोग करें ताकि आपकी सटीक लोकेशन जल्दी साझा हो सके।',
      'dash_fetching_location': 'लोकेशन ली जा रही है...',
      'dash_get_live_location': 'लाइव लोकेशन लें',
      'dash_location_service_disabled': 'लोकेशन सेवा बंद है।',
      'dash_location_permission_denied': 'लोकेशन अनुमति नहीं मिली।',
      'dash_location_fetch_failed': 'लाइव लोकेशन प्राप्त नहीं हो सकी।',
      'dash_lat_lng': 'अक्षांश {lat}, देशांतर {lng}',
      'dash_copy_help': 'मदद संदेश कॉपी करें',
      'dash_open_maps': 'मैप में खोलें',
      'dash_help_message_template': 'आपात मदद चाहिए। वर्तमान लोकेशन: {url}',
      'dash_emergency_actions': 'आपात कार्रवाई',
      'dash_quick_guide_title': 'त्वरित मार्गदर्शिका',
      'dash_quick_step_1_title': '1. अलर्ट देखें',
      'dash_quick_step_1_subtitle':
          'अपने क्षेत्र में वर्तमान जोखिम की पुष्टि के लिए Alerts खोलें।',
      'dash_quick_step_2_title': '2. बाढ़ रिपोर्ट करें',
      'dash_quick_step_2_subtitle':
          'अपनी लोकेशन से पानी का स्तर और बाढ़ फोटो भेजें।',
      'dash_quick_step_3_title': '3. मदद / सुरक्षित क्षेत्र',
      'dash_quick_step_3_subtitle':
          'तात्कालिक सहायता के लिए Help और निकासी के लिए Safe Zones उपयोग करें।',
      'help_title': 'मदद अनुरोध',
      'help_desc':
          'तुरंत सहायता के लिए वन-टैप फ्लो। श्रेणी चुनें, संपर्क नंबर डालें, और वैकल्पिक लोकेशन जोड़ें।',
      'help_category_medical': 'मेडिकल',
      'help_category_evacuation': 'निकासी',
      'help_category_food_water': 'खाना/पानी',
      'help_contact_label': 'संपर्क नंबर',
      'help_contact_hint': 'उदाहरण: 9876543210',
      'help_attach_location_optional': 'लाइव लोकेशन जोड़ें (वैकल्पिक)',
      'help_detecting': 'पता लगाया जा रहा है...',
      'help_live_location_attached': 'लाइव लोकेशन जोड़ दी गई।',
      'help_live_location_fetch_failed': 'लाइव लोकेशन प्राप्त नहीं हो सकी।',
      'help_send': 'मदद अनुरोध भेजें',
      'help_sending': 'भेजा जा रहा है...',
      'help_invalid_contact': 'कृपया सही संपर्क नंबर दर्ज करें।',
      'help_sent_success': 'मदद अनुरोध सफलतापूर्वक भेज दिया गया।',
      'help_rejected': 'सर्वर ने मदद अनुरोध अस्वीकार कर दिया।',
      'help_saved_offline': 'नेटवर्क नहीं है। मदद अनुरोध ऑफलाइन सेव हुआ।',
      'help_location_service_disabled': 'लोकेशन सेवा बंद है',
      'help_location_permission_denied': 'लोकेशन अनुमति नहीं मिली',
      'help_tracking_title': 'मदद अनुरोध ट्रैकिंग',
      'help_tracking_empty': 'अभी तक कोई मदद अनुरोध ट्रैक नहीं हुआ।',
      'help_tracking_updated': 'मदद अनुरोध स्थिति रिफ्रेश की गई।',
      'help_status_sent': 'भेजा गया',
      'help_status_received': 'प्राप्त',
      'help_status_assigned': 'असाइन',
      'help_status_closed': 'बंद',
      'help_status_pending': 'ऑफलाइन लंबित',
      'help_status_failed': 'असफल',
      'help_track_created': 'बनाया गया {ago}',
      'help_pending_title': 'ऑफलाइन लंबित मदद अनुरोध',
      'help_pending_count': 'लंबित अनुरोध: {count}',
      'help_sync_pending_button': 'लंबित अनुरोध सिंक करें ({count})',
      'help_syncing': 'सिंक हो रहा है...',
      'help_sync_none': 'सिंक के लिए कोई लंबित मदद अनुरोध नहीं है।',
      'help_sync_summary':
          '{synced} अनुरोध सिंक, {failed} असफल, {pending} लंबित।',
      'report_loc_service_disabled': 'लोकेशन सेवा बंद है',
      'report_loc_permission_denied': 'लोकेशन अनुमति नहीं मिली',
      'report_sync_none': 'सिंक करने के लिए कोई ऑफलाइन रिपोर्ट लंबित नहीं है।',
      'report_sync_summary':
          '{synced} रिपोर्ट सिंक, {failed} फेल, {pending} पेंडिंग।',
      'report_invalid_pincode': 'कृपया सही 6-अंकों का पिनकोड दर्ज करें।',
      'report_enter_custom_zone': 'कृपया कस्टम ज़ोन आईडी दर्ज करें।',
      'report_detected_area': 'पहचाना गया क्षेत्र: {city}, {area} ({pincode})',
      'report_gps_custom_created':
          'ज्ञात क्षेत्र नहीं मिला। कस्टम GPS ज़ोन आईडी बनाई गई।',
      'report_unable_detect_location': 'वर्तमान लोकेशन पता नहीं की जा सकी।',
      'report_unable_access_camera_gallery':
          'कैमरा/गैलरी का उपयोग नहीं हो सका।',
      'report_submission_failed_water': 'पानी स्तर रिपोर्ट भेजने में विफल।',
      'report_saved_offline_pending':
          'नेटवर्क नहीं है। पानी स्तर ऑफलाइन सेव हुआ। लंबित: {count}।',
      'report_photo_required': 'कृपया बाढ़ फोटो लें या चुनें।',
      'report_submission_failed_photo': 'बाढ़ फोटो भेजने में विफल।',
      'report_section_location_zone': 'लोकेशन ज़ोन',
      'report_mode_area_pincode': 'क्षेत्र + पिनकोड',
      'report_mode_custom': 'कस्टम आईडी',
      'report_detecting_location': 'लोकेशन पता लगाई जा रही है...',
      'report_use_gps_autodetect': 'GPS से क्षेत्र स्वतः पहचानें',
      'report_city_district': 'शहर / जिला',
      'report_area_suggestions': 'क्षेत्र सुझाव',
      'report_clear_selected_area': 'चुना क्षेत्र साफ करें',
      'report_suggested_areas': 'सुझाए गए क्षेत्र',
      'report_suggested_helper':
          'सूची से चुनें, या नीचे अपना क्षेत्र टाइप करें।',
      'report_select_area_optional': 'क्षेत्र चुनें (वैकल्पिक)',
      'report_locality_label': 'क्षेत्र / लोकैलिटी (मैनुअल वैकल्पिक)',
      'report_locality_hint': 'अपना क्षेत्र या मोहल्ला दर्ज करें',
      'report_locality_helper':
          'यदि आपका क्षेत्र ड्रॉपडाउन में नहीं है तो इसका उपयोग करें।',
      'report_pincode_label': 'पिनकोड',
      'report_pincode_hint': '6-अंकों का पिनकोड',
      'report_my_area_use': 'मेरा क्षेत्र उपयोग करें',
      'report_my_area_save': 'मेरा क्षेत्र सेव करें',
      'report_my_area_clear_saved': 'सेव किया क्षेत्र हटाएं',
      'report_my_area_saved': 'आपका डिफॉल्ट क्षेत्र सेव हो गया।',
      'report_my_area_applied': 'सेव किया क्षेत्र लागू कर दिया गया।',
      'report_my_area_cleared': 'सेव किया डिफॉल्ट क्षेत्र हटाया गया।',
      'report_my_area_missing': 'अभी कोई सेव किया क्षेत्र नहीं मिला।',
      'report_generated_zone_id': 'जनरेटेड ज़ोन आईडी: {zone}',
      'report_custom_zone_id_label': 'कस्टम ज़ोन आईडी',
      'report_custom_zone_id_hint': 'उदाहरण: WARD-12 या GPS-19.0178-72.8478',
      'report_section_flood_photo': 'बाढ़ फोटो',
      'report_camera': 'कैमरा',
      'report_gallery': 'गैलरी',
      'report_selected_file': 'चयनित: {name}',
      'report_submitting': 'भेजा जा रहा है...',
      'report_submit_flood_photo': 'बाढ़ फोटो भेजें',
      'report_section_flooding_level': 'बाढ़ स्तर',
      'report_submit_water_level': 'पानी स्तर भेजें',
      'report_syncing_pending': 'लंबित सिंक हो रहा है...',
      'report_sync_pending_button': 'लंबित पानी रिपोर्ट सिंक करें ({count})',
      'alerts_load_failed': 'अलर्ट लोड नहीं हो सके।',
      'alerts_empty': 'अभी कोई अलर्ट उपलब्ध नहीं है।',
      'alerts_offline_banner':
          'ऑफलाइन मोड: आखिरी सेव किए हुए अलर्ट दिख रहे हैं।',
      'alerts_feed_title': 'अलर्ट फीड',
      'alerts_count': '{count} अलर्ट',
      'alerts_updated': 'अपडेट: {ago}',
      'alerts_channel': 'चैनल: {channel}',
      'safezones_load_failed': 'सुरक्षित क्षेत्र लोड नहीं हो सके।',
      'safezones_unavailable_title': 'सुरक्षित क्षेत्र फिलहाल उपलब्ध नहीं हैं।',
      'safezones_unavailable_help':
          'नेटवर्क जांचें और फिर से प्रयास करें। इस पेज को नीचे खींचकर रिफ्रेश भी कर सकते हैं।',
      'safezones_retry_hint':
          'अगर सेव किए हुए सुरक्षित क्षेत्र उपलब्ध होंगे, तो वे अपने आप दिख जाएंगे।',
      'safezones_empty': 'अभी कोई सक्रिय सुरक्षित क्षेत्र उपलब्ध नहीं है।',
      'safezones_offline_banner':
          'ऑफलाइन मोड: आखिरी सेव किए हुए सुरक्षित क्षेत्र दिख रहे हैं।',
      'safezones_locating': 'लोकेशन खोजी जा रही है...',
      'safezones_use_location': 'मेरी लोकेशन उपयोग करें',
      'safezones_distance_hidden': 'लोकेशन सक्षम होने तक दूरी छुपी रहेगी।',
      'safezones_distance_shown': 'अब आपकी लोकेशन से दूरी दिखाई जा रही है।',
      'safezones_last_updated': 'सुरक्षित क्षेत्र अंतिम अपडेट: {ago}',
      'safezones_nearest': 'सबसे नज़दीकी सुरक्षित क्षेत्र: {zoneId}',
      'safezones_distance_eta': 'दूरी: {km} किमी | ETA: ~{eta} मिनट',
      'safezones_active_count': 'सक्रिय सुरक्षित क्षेत्र: {count}',
      'safezones_unnamed_zone': 'बिना नाम का क्षेत्र',
      'safezones_coords': 'अक्षांश {lat}, देशांतर {lng}',
      'safezones_area_pincode': 'क्षेत्र: {area} | पिनकोड: {pincode}',
      'safezones_source_confidence':
          'स्रोत: {source} | विश्वसनीयता: {confidence}',
      'safezones_area_unavailable': 'क्षेत्र उपलब्ध नहीं',
      'safezones_location_fetch_failed': 'वर्तमान लोकेशन प्राप्त नहीं हो सकी।',
      'safezones_open_route': 'सुरक्षित मार्ग खोलें',
      'safezones_route_tip':
          'चलते समय मुख्य सड़कों का उपयोग करें और दिखने वाले जलभराव से बचें।',
      'safezones_route_open_failed': 'मैप में मार्ग नहीं खुल सका।',
      'myreports_load_failed': 'रिपोर्ट हिस्ट्री लोड नहीं हो सकी।',
      'myreports_title': 'मेरी रिपोर्ट',
      'myreports_count': '{count} रिपोर्ट',
      'myreports_synced': 'सिंक: {count}',
      'myreports_pending': 'पेंडिंग: {count}',
      'myreports_failed': 'फेल: {count}',
      'myreports_empty': 'अभी रिपोर्ट हिस्ट्री नहीं है।',
      'myreports_type_water_level': 'पानी का स्तर',
      'myreports_type_flood_photo': 'बाढ़ फोटो',
      'myreports_status_synced': 'सिंक',
      'myreports_status_pending': 'पेंडिंग',
      'myreports_status_failed': 'फेल',
      'myreports_zone': 'ज़ोन: {zone}',
      'myreports_level': 'स्तर: {level}',
      'myreports_created': 'बनाया गया {ago}',
      'myreports_updated': 'अपडेट {ago}',
      'trust_title': 'ऐप भाषा',
      'trust_desc':
          'आपात स्थिति में साफ निर्देशों के लिए अपनी पसंदीदा भाषा चुनें।',
      'trust_language_label': 'भाषा',
      'trust_data_saver_title': 'डेटा सेवर मोड',
      'trust_data_saver_desc':
          'डेटा बचाने के लिए Alerts और Safe Zones का बैकग्राउंड रिफ्रेश कम करता है।',
      'lang_english': 'अंग्रेज़ी',
      'lang_hindi': 'हिंदी',
      'lang_marathi': 'मराठी',
    },
    'mr': <String, String>{
      'title_dashboard': 'नागरिक डॅशबोर्ड',
      'title_alerts': 'अलर्ट',
      'title_report': 'पूर नोंद',
      'title_safe_zones': 'सुरक्षित क्षेत्रे',
      'title_request_help': 'मदत विनंती',
      'title_my_reports': 'माझे अहवाल',
      'title_trust': 'अॅप भाषा',
      'menu': 'नागरिक मेनू',
      'navigation': 'नेव्हिगेशन',
      'dashboard': 'डॅशबोर्ड',
      'alerts': 'अलर्ट',
      'report': 'पूर नोंद',
      'safe_zones': 'सुरक्षित क्षेत्रे',
      'request_help': 'मदत विनंती',
      'my_reports': 'माझे अहवाल',
      'trust': 'अॅप भाषा',
      'language_tooltip': 'भाषा',
      'retry': 'पुन्हा प्रयत्न करा',
      'call': 'कॉल',
      'time_unknown': 'अज्ञात',
      'time_just_now': 'आत्ताच',
      'time_min_ago': '{value} मिनिटांपूर्वी',
      'time_hr_ago': '{value} तासांपूर्वी',
      'time_day_ago': '{value} दिवसांपूर्वी',
      'dash_call_failed': '{number} वर कॉल करता आला नाही',
      'dash_location_copied': 'शेअर करण्यासाठी लोकेशन कॉपी केले.',
      'dash_summary_fetch_failed': 'लाइव्ह सारांश मिळाला नाही.',
      'dash_stay_alert_title': 'सावध रहा. पूराची नोंद पटकन करा.',
      'dash_stay_alert_subtitle':
          'या अॅपद्वारे पूर फोटो पाठवा, पाण्याची पातळी शेअर करा आणि जवळची सुरक्षित क्षेत्रे शोधा.',
      'dash_btn_report': 'आत्ता पूराची नोंद करा',
      'dash_btn_alerts': 'अलर्ट पहा',
      'dash_btn_safe_zones': 'सुरक्षित क्षेत्र नकाशा उघडा',
      'dash_btn_request_help': 'मदत मागा',
      'dash_btn_my_reports': 'माझ्या नोंदींचा इतिहास',
      'dash_live_snapshot': 'लाइव्ह स्नॅपशॉट',
      'dash_loading_live': 'लाइव्ह माहिती लोड होत आहे...',
      'dash_active_safe_zones': 'सध्या उपलब्ध सुरक्षित क्षेत्रे: {count}',
      'dash_active_alerts': 'आताचे लाइव्ह अलर्ट: {count}',
      'dash_safe_zones_updated': 'सुरक्षित क्षेत्र डेटा शेवटचा अपडेट: {ago}',
      'dash_alerts_fetch_failed': 'लाइव्ह अलर्ट मिळाले नाहीत.',
      'dash_no_live_alerts': 'सध्या कोणतेही लाइव्ह अलर्ट नाहीत.',
      'dash_view_alerts_feed': 'अलर्ट फीड पहा',
      'dash_what_to_report': 'काय नोंदवायचे',
      'dash_report_point_1':
          '1. रस्ते आणि पाण्याच्या हालचालींचे स्पष्ट फोटो घ्या.',
      'dash_report_point_2':
          '2. जवळचा झोन आयडी निवडा आणि पाण्याची सद्य पातळी पाठवा.',
      'dash_report_point_3': '3. पूर वाढल्यास पुन्हा अपडेट पाठवा.',
      'dash_immediate_safety': 'तात्काळ सुरक्षितता',
      'dash_safety_point_1': 'खोल सखल रस्ते आणि अंडरपास टाळा.',
      'dash_safety_point_2':
          'चिन्हांकित सुरक्षित क्षेत्रात जा आणि अपडेट पाहत रहा.',
      'dash_safety_point_3':
          'तातडीच्या धोक्यात स्थानिक आपत्कालीन सेवांना कॉल करा.',
      'dash_safety_point_4':
          'जोरदार पाऊस सुरू झाल्यावर फोन बॅटरी 50% पेक्षा जास्त ठेवा.',
      'dash_safety_point_5':
          'हलण्यापूर्वी कुटुंबासोबत सत्यापित लोकेशन शेअर करा.',
      'dash_safety_freshness':
          'सुरक्षित क्षेत्र डेटा ताजेपणा: {ago} पूर्वी अपडेट.',
      'dash_helplines': 'आपत्कालीन हेल्पलाइन',
      'dash_select_area': 'जिल्हानिहाय मार्गदर्शनासाठी आपला भाग निवडा:',
      'dash_area_label': 'भाग',
      'dash_helpline_national': 'राष्ट्रीय आपत्कालीन प्रतिसाद',
      'dash_helpline_fire': 'अग्निशमन दल',
      'dash_helpline_ambulance': 'रुग्णवाहिका / वैद्यकीय आपत्काल',
      'dash_helpline_area_support': '{area} आपत्कालीन मदत',
      'dash_helpline_tip':
          'सूचना: जलद प्रतिसादासाठी कॉल करताना अचूक भाग सांगा.',
      'dash_live_location_title': 'मदतीसाठी लाइव्ह लोकेशन',
      'dash_live_location_desc':
          'गरज असल्यासच वापरा, म्हणजे प्रतिसादकांना तुमची अचूक लोकेशन पटकन देता येईल.',
      'dash_fetching_location': 'लोकेशन घेत आहे...',
      'dash_get_live_location': 'लाइव्ह लोकेशन घ्या',
      'dash_location_service_disabled': 'लोकेशन सेवा बंद आहे.',
      'dash_location_permission_denied': 'लोकेशन परवानगी नाकारली गेली.',
      'dash_location_fetch_failed': 'लाइव्ह लोकेशन मिळाली नाही.',
      'dash_lat_lng': 'अक्षांश {lat}, रेखांश {lng}',
      'dash_copy_help': 'मदत संदेश कॉपी करा',
      'dash_open_maps': 'नकाशात उघडा',
      'dash_help_message_template':
          'आपत्कालीन मदत हवी आहे. सध्याचे लोकेशन: {url}',
      'dash_emergency_actions': 'आपत्कालीन कृती',
      'dash_quick_guide_title': 'त्वरित मार्गदर्शक',
      'dash_quick_step_1_title': '1. अलर्ट तपासा',
      'dash_quick_step_1_subtitle':
          'आपल्या भागातील सध्याचा धोका तपासण्यासाठी Alerts उघडा.',
      'dash_quick_step_2_title': '2. पूराची नोंद करा',
      'dash_quick_step_2_subtitle':
          'आपल्या लोकेशनवरून पाण्याची पातळी आणि पूर फोटो पाठवा.',
      'dash_quick_step_3_title': '3. मदत / सुरक्षित क्षेत्रे',
      'dash_quick_step_3_subtitle':
          'तातडीच्या मदतीसाठी Help आणि स्थलांतरासाठी Safe Zones वापरा.',
      'help_title': 'मदत विनंती',
      'help_desc':
          'तातडीच्या मदतीसाठी वन-टॅप फ्लो. श्रेणी निवडा, संपर्क क्रमांक भरा आणि पर्यायी लोकेशन जोडा.',
      'help_category_medical': 'वैद्यकीय',
      'help_category_evacuation': 'स्थलांतर',
      'help_category_food_water': 'अन्न/पाणी',
      'help_contact_label': 'संपर्क क्रमांक',
      'help_contact_hint': 'उदाहरण: 9876543210',
      'help_attach_location_optional': 'लाइव्ह लोकेशन जोडा (पर्यायी)',
      'help_detecting': 'शोधत आहे...',
      'help_live_location_attached': 'लाइव्ह लोकेशन जोडली.',
      'help_live_location_fetch_failed': 'लाइव्ह लोकेशन मिळाली नाही.',
      'help_send': 'मदत विनंती पाठवा',
      'help_sending': 'पाठवत आहे...',
      'help_invalid_contact': 'वैध संपर्क क्रमांक भरा.',
      'help_sent_success': 'मदत विनंती यशस्वीपणे पाठवली.',
      'help_rejected': 'सर्व्हरने मदत विनंती नाकारली.',
      'help_saved_offline': 'नेटवर्क नाही. मदत विनंती ऑफलाइन सेव झाली.',
      'help_location_service_disabled': 'लोकेशन सेवा बंद आहे',
      'help_location_permission_denied': 'लोकेशन परवानगी नाकारली',
      'help_tracking_title': 'मदत विनंती ट्रॅकिंग',
      'help_tracking_empty': 'अद्याप कोणतीही मदत विनंती ट्रॅक झालेली नाही.',
      'help_tracking_updated': 'मदत विनंती स्थिती रिफ्रेश केली.',
      'help_status_sent': 'पाठवले',
      'help_status_received': 'स्वीकारले',
      'help_status_assigned': 'नेमले',
      'help_status_closed': 'बंद',
      'help_status_pending': 'ऑफलाइन प्रलंबित',
      'help_status_failed': 'अयशस्वी',
      'help_track_created': 'तयार {ago}',
      'help_pending_title': 'ऑफलाइन प्रलंबित मदत विनंत्या',
      'help_pending_count': 'प्रलंबित विनंत्या: {count}',
      'help_sync_pending_button': 'प्रलंबित विनंत्या सिंक करा ({count})',
      'help_syncing': 'सिंक होत आहे...',
      'help_sync_none': 'सिंक करण्यासाठी प्रलंबित मदत विनंत्या नाहीत.',
      'help_sync_summary':
          '{synced} विनंत्या सिंक, {failed} अयशस्वी, {pending} प्रलंबित.',
      'report_loc_service_disabled': 'लोकेशन सेवा बंद आहे',
      'report_loc_permission_denied': 'लोकेशन परवानगी नाकारली',
      'report_sync_none':
          'सिंक करण्यासाठी कोणतेही ऑफलाइन अहवाल प्रलंबित नाहीत.',
      'report_sync_summary':
          '{synced} अहवाल सिंक, {failed} अयशस्वी, {pending} प्रलंबित.',
      'report_invalid_pincode': 'कृपया वैध 6-अंकी पिनकोड भरा.',
      'report_enter_custom_zone': 'कृपया कस्टम झोन आयडी भरा.',
      'report_detected_area': 'ओळखलेला भाग: {city}, {area} ({pincode})',
      'report_gps_custom_created':
          'ओळखीच्या भागाशी जुळवता आले नाही. कस्टम GPS झोन आयडी तयार केली.',
      'report_unable_detect_location': 'सध्याची लोकेशन ओळखता आली नाही.',
      'report_unable_access_camera_gallery': 'कॅमेरा/गॅलरी वापरता आली नाही.',
      'report_submission_failed_water': 'पाण्याची पातळी पाठवण्यात अयशस्वी.',
      'report_saved_offline_pending':
          'नेटवर्क नाही. पाण्याची पातळी ऑफलाइन सेव झाली. प्रलंबित: {count}.',
      'report_photo_required': 'कृपया पूर फोटो घ्या किंवा निवडा.',
      'report_submission_failed_photo': 'पूर फोटो पाठवण्यात अयशस्वी.',
      'report_section_location_zone': 'लोकेशन झोन',
      'report_mode_area_pincode': 'भाग + पिनकोड',
      'report_mode_custom': 'कस्टम आयडी',
      'report_detecting_location': 'लोकेशन शोधत आहे...',
      'report_use_gps_autodetect': 'GPS वापरून भाग स्वयंचलित शोधा',
      'report_city_district': 'शहर / जिल्हा',
      'report_area_suggestions': 'भाग सूचना',
      'report_clear_selected_area': 'निवडलेला भाग साफ करा',
      'report_suggested_areas': 'सुचवलेले भाग',
      'report_suggested_helper':
          'यादीतून निवडा किंवा खाली स्वतःचा भाग टाइप करा.',
      'report_select_area_optional': 'भाग निवडा (पर्यायी)',
      'report_locality_label': 'भाग / परिसर (मॅन्युअल पर्यायी)',
      'report_locality_hint': 'आपला भाग किंवा परिसर भरा',
      'report_locality_helper': 'तुमचा भाग ड्रॉपडाउनमध्ये नसल्यास हे वापरा.',
      'report_pincode_label': 'पिनकोड',
      'report_pincode_hint': '6-अंकी पिनकोड',
      'report_my_area_use': 'माझा भाग वापरा',
      'report_my_area_save': 'माझा भाग सेव करा',
      'report_my_area_clear_saved': 'सेव केलेला भाग काढा',
      'report_my_area_saved': 'तुमचा डीफॉल्ट भाग सेव केला.',
      'report_my_area_applied': 'सेव केलेला भाग लागू केला.',
      'report_my_area_cleared': 'सेव केलेला डीफॉल्ट भाग काढला.',
      'report_my_area_missing': 'अद्याप सेव केलेला भाग सापडला नाही.',
      'report_generated_zone_id': 'तयार झालेली झोन आयडी: {zone}',
      'report_custom_zone_id_label': 'कस्टम झोन आयडी',
      'report_custom_zone_id_hint': 'उदा: WARD-12 किंवा GPS-19.0178-72.8478',
      'report_section_flood_photo': 'पूर फोटो',
      'report_camera': 'कॅमेरा',
      'report_gallery': 'गॅलरी',
      'report_selected_file': 'निवडलेले: {name}',
      'report_submitting': 'पाठवत आहे...',
      'report_submit_flood_photo': 'पूर फोटो पाठवा',
      'report_section_flooding_level': 'पूर पातळी',
      'report_submit_water_level': 'पाण्याची पातळी पाठवा',
      'report_syncing_pending': 'प्रलंबित सिंक होत आहे...',
      'report_sync_pending_button': 'प्रलंबित पाणी अहवाल सिंक करा ({count})',
      'alerts_load_failed': 'अलर्ट लोड करता आले नाहीत.',
      'alerts_empty': 'सध्या कोणतेही अलर्ट उपलब्ध नाहीत.',
      'alerts_offline_banner':
          'ऑफलाइन मोड: शेवटचे सेव केलेले अलर्ट दाखवत आहोत.',
      'alerts_feed_title': 'अलर्ट फीड',
      'alerts_count': '{count} अलर्ट',
      'alerts_updated': 'अपडेट: {ago}',
      'alerts_channel': 'चॅनेल: {channel}',
      'safezones_load_failed': 'सुरक्षित क्षेत्रे लोड करता आली नाहीत.',
      'safezones_unavailable_title': 'सुरक्षित क्षेत्रे सध्या उपलब्ध नाहीत.',
      'safezones_unavailable_help':
          'नेटवर्क तपासा आणि पुन्हा प्रयत्न करा. हे पेज खाली ओढून रिफ्रेश करू शकता.',
      'safezones_retry_hint':
          'सेव्ह केलेली सुरक्षित क्षेत्रे उपलब्ध असतील तर ती आपोआप दाखवली जातील.',
      'safezones_empty': 'सध्या सक्रिय सुरक्षित क्षेत्र उपलब्ध नाहीत.',
      'safezones_offline_banner':
          'ऑफलाइन मोड: शेवटची सेव केलेली सुरक्षित क्षेत्रे दाखवत आहोत.',
      'safezones_locating': 'लोकेशन शोधत आहे...',
      'safezones_use_location': 'माझी लोकेशन वापरा',
      'safezones_distance_hidden': 'लोकेशन सुरू होईपर्यंत अंतर दिसणार नाही.',
      'safezones_distance_shown': 'आता तुमच्या लोकेशनवरून अंतर दाखवले जात आहे.',
      'safezones_last_updated': 'सुरक्षित क्षेत्र शेवटचे अपडेट: {ago}',
      'safezones_nearest': 'सर्वात जवळचे सुरक्षित क्षेत्र: {zoneId}',
      'safezones_distance_eta': 'अंतर: {km} किमी | ETA: ~{eta} मिनिटे',
      'safezones_active_count': 'सक्रिय सुरक्षित क्षेत्रे: {count}',
      'safezones_unnamed_zone': 'अनामिक क्षेत्र',
      'safezones_coords': 'अक्षांश {lat}, रेखांश {lng}',
      'safezones_area_pincode': 'भाग: {area} | पिनकोड: {pincode}',
      'safezones_source_confidence':
          'स्रोत: {source} | विश्वसनीयता: {confidence}',
      'safezones_area_unavailable': 'भाग उपलब्ध नाही',
      'safezones_location_fetch_failed': 'सध्याची लोकेशन मिळाली नाही.',
      'safezones_open_route': 'सुरक्षित मार्ग उघडा',
      'safezones_route_tip':
          'हलताना मुख्य रस्ते वापरा आणि दिसणारे पाणथळ मार्ग टाळा.',
      'safezones_route_open_failed': 'नकाशात मार्ग उघडता आला नाही.',
      'myreports_load_failed': 'अहवाल इतिहास लोड करता आला नाही.',
      'myreports_title': 'माझे अहवाल',
      'myreports_count': '{count} अहवाल',
      'myreports_synced': 'सिंक: {count}',
      'myreports_pending': 'प्रलंबित: {count}',
      'myreports_failed': 'अयशस्वी: {count}',
      'myreports_empty': 'अद्याप अहवाल इतिहास नाही.',
      'myreports_type_water_level': 'पाण्याची पातळी',
      'myreports_type_flood_photo': 'पूर फोटो',
      'myreports_status_synced': 'सिंक',
      'myreports_status_pending': 'प्रलंबित',
      'myreports_status_failed': 'अयशस्वी',
      'myreports_zone': 'झोन: {zone}',
      'myreports_level': 'पातळी: {level}',
      'myreports_created': 'तयार {ago}',
      'myreports_updated': 'अपडेट {ago}',
      'trust_title': 'अॅप भाषा',
      'trust_desc':
          'आपत्कालीन स्थितीत स्पष्ट सूचना मिळण्यासाठी आपली पसंतीची भाषा निवडा.',
      'trust_language_label': 'भाषा',
      'trust_data_saver_title': 'डेटा सेवर मोड',
      'trust_data_saver_desc':
          'डेटा वाचवण्यासाठी Alerts आणि Safe Zones चे पार्श्वभूमी रिफ्रेश कमी करते.',
      'lang_english': 'इंग्रजी',
      'lang_hindi': 'हिंदी',
      'lang_marathi': 'मराठी',
    },
  };

  static String tr(String key, String languageCode) {
    final Map<String, String> dictionary =
        _values[languageCode] ?? _values['en']!;
    return dictionary[key] ?? _values['en']![key] ?? key;
  }

  static String trf(
    String key,
    String languageCode, [
    Map<String, String> params = const <String, String>{},
  ]) {
    String text = tr(key, languageCode);
    params.forEach((String param, String value) {
      text = text.replaceAll('{$param}', value);
    });
    return text;
  }

  static String relativeTimeFromNow(DateTime timestamp, String languageCode) {
    final Duration diff = DateTime.now().difference(timestamp);
    if (diff.isNegative || diff.inSeconds < 60) {
      return tr('time_just_now', languageCode);
    }
    if (diff.inMinutes < 60) {
      return trf('time_min_ago', languageCode, <String, String>{
        'value': diff.inMinutes.toString(),
      });
    }
    if (diff.inHours < 24) {
      return trf('time_hr_ago', languageCode, <String, String>{
        'value': diff.inHours.toString(),
      });
    }
    return trf('time_day_ago', languageCode, <String, String>{
      'value': diff.inDays.toString(),
    });
  }
}
